spring:
  datasource:
    druid:
      username: root
      password: cpy990923
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/inepp_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update