server:
  port: 8092
spring:
  profiles:
    active: common,domain
  redis:
    host: localhost
    database: 0
    port: 6379


  activemq:
    broker-url: tcp://192.168.43.26:61616
    user: admin
    password: admin
    close-timeout: 15s
    in-memory: true
    packages:
      trust-all: true

